### ISSUE TITLE
Move User Selector from Home tab to Settings tab

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/app#55]
If only email, only show email with the white text in a single row.
If name, name is white text, email is grey text, and two rows.

Like so:

<img width="483" alt="Screen Shot 2024-08-25 at 11 52 09 AM" src="https://github.com/user-attachments/assets/0bacb5d1-b76b-41d5-b339-df96a250848e">

**Comment by pavlenex** [comment]
@dennisreimann considering in https://github.com/btcpayserver/app/commit/fecd4c59c6a8d85bc6f8cb87e3f04ce0f4636dfd you moved this one out, should we remove it entirely from the dashboard, since it really doesn't give any value, and once that is done that would complete this issue? WDYT?

<img width="1217" alt="Screenshot 2024-11-29 at 13 42 19" src="https://github.com/user-attachments/assets/0ba16920-9d1b-4875-a03e-722091318f64">

**Comment by dennisreimann** [comment]
My idea was to have the user switch there, if the store has multiple users. We could of course bring this to the Settings as well, however you think it is best.

**Comment by pavlenex** [comment]
I am just not sure it's good to duplicate similar functionality in an inconsistent way, especially since people are used to logging off whenever there's a profile context. I get that we want to keep the switch accessible, but settings > user is pretty good tradeoff vs having it in an inconsistent way in two places. Up to @dstrukt I guess.

**Comment by dstrukt** [comment]
I think it probably makes sense to push it all to the Settings view for now, until we get a strong signal that users want to switch in this view (which they can do in Settings), so no need to duplicate for now, we also might need that top left corner real-estate.

**Comment by dennisreimann** [comment]
The user switch changes aren't fully implemented yet, but this is what it looks like now:

![user-switch](https://github.com/user-attachments/assets/9bcb8acd-83f7-4df2-83d5-1cae712c4ff5)
